services:
  monero-wallet-rpc:
    image: normoes/monero:v0.17.3.0
    command: monero-wallet-rpc --wallet-file wallet --password-file wallet.passwd --disable-rpc-login
    volumes:
      - ./data/wallet:/monero
    environment:
      - DAEMON_HOST=${MONERO_DAEMON_RPC_HOSTNAME}
      - DAEMON_PORT=${MONERO_DAEMON_RPC_PORT}
      - RPC_USER=${MONERO_DAEMON_RPC_USERNAME}
      - RPC_PASSWD=${MONERO_DAEMON_RPC_PASSWORD}
    restart: unless-stopped

  postgresql:
    image: postgres:14-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: unless-stopped

  moneropay:
    image: registry.gitlab.com/moneropay/moneropay:v2
    environment:
      - RPC_ADDRESS=http://monero-wallet-rpc:28081/json_rpc
      - POSTGRESQL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DATABASE}
    depends_on:
      - monero-wallet-rpc
      - postgresql
    restart: unless-stopped
