services:
  monero-wallet-rpc:
    image: ghcr.io/sethforprivacy/simple-monero-wallet-rpc:v0.18.1.2
    command: --wallet-file wallet --password-file wallet.passwd --disable-rpc-login --rpc-bind-port=28081 --daemon-host=${MONERO_DAEMON_RPC_HOSTNAME} --daemon-port=${MONERO_DAEMON_RPC_PORT} --max-log-files=0 --max-log-file-size=0
    volumes:
      - ./data/wallet:/home/monero/wallet
    restart: unless-stopped

  postgresql:
    image: postgres:14-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: unless-stopped

  moneropay:
    image: registry.gitlab.com/moneropay/moneropay:v2
    environment:
      - RPC_ADDRESS=http://monero-wallet-rpc:28081/json_rpc
      - POSTGRESQL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DATABASE}?sslmode=disable
    depends_on:
      - monero-wallet-rpc
      - postgresql
    restart: unless-stopped
